name: LordMike Release CI

on:
  push:
    tags:
      - '*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  wled_build:
    uses: ./.github/workflows/build.yml
    with:
      release: true
      release_config: .github/platformio_lordmike_release.ini.template

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: wled_build
    steps:
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Create draft release
      uses: softprops/action-gh-release@v1
      with:
        body: "Release assets uploaded. Release notes pending..."
        draft: true
        files: |
          *.bin
          *.bin.gz
